@server= http://localhost:3000/posts

### gustavo
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1OWNhMDUxOTlhNGRlOTEzMGQ1M2EzOCIsImlhdCI6MTcwNTgwNDg1MCwiZXhwIjoxNzA2NDA5NjUwfQ.xOr-BIuJEIr-udIdcBRZGz8yk02QWApahWiYTGH9nfk

### santiago
#@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1OWNhYTRiOTlhNGRlOTEzMGQ1M2EzYiIsImlhdCI6MTcwNTgwNDk1OCwiZXhwIjoxNzA2NDA5NzU4fQ.SgYxbF87ppfmSG-WQmSbfFV3O9pabByJ2h5DIrNvZek

### amanda
#@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YTQ1NDlkYmY5YTNlMzlkMGQwNzhmNSIsImlhdCI6MTcwNTgwNTAyOSwiZXhwIjoxNzA2NDA5ODI5fQ.mvobl40mnQ4WpovmWwRK6v9gmYt01BlrrwxeSKmU4Zg

### Crear post directamente
POST {{server}}/
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "title": "Especies en Peligro de Extinción: Una Llamada a la Acción falso",
    "content": "Conoce más sobre las especies en peligro de extinción y descubre cómo puedes contribuir a su conservación y preservación.",
    "category": [
        "medio ambiente", "conservación"
    ]
}


### Obtener todos los post
GET {{server}}?skip=10&limit=10
Authorization: Bearer {{token}}

### Obtener post por id
GET {{server}}/65809c35f6b619bdd98cde6f
Authorization: Bearer {{token}}

### Obtener posts por id
GET {{server}}/user/6580648ed072726fda77ef0a
Authorization: Bearer {{token}}

### Actualizar datos del post
PUT {{server}}/657fadcec3d258853ea6c81a
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "primer post editado2",
    "content": "Este sera el primer post que genere para el blog que nos pidieron en el bootcamp",
    "category": [
      "informatica", "actualidad"
    ]
}

### Eliminar un post por autor o admin
DELETE  {{server}}/65ac8e2c19cbe75795bca604
Authorization: Bearer {{token}}

### filtra los posts por querys en base a parametros como el contenido o el titulo
GET {{server}}/search?search=reclamo
Authorization: Bearer {{token}}

### filtra los posts por querys en base a categorias o autores
GET {{server}}/filter?category=geografia
Authorization: Bearer {{token}}

