@server= http://localhost:3000/users


@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1OWNhMDUxOTlhNGRlOTEzMGQ1M2EzOCIsImlhdCI6MTcwNTgwMjk0NywiZXhwIjoxNzA2NDA3NzQ3fQ.Va6GZ6oQYPdJQcL-tFo3Wcu6Mw06HyKJF96RCkNnIJE

#@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YTQ1NDlkYmY5YTNlMzlkMGQwNzhmNSIsImlhdCI6MTcwNTI3MDQxNiwiZXhwIjoxNzA1ODc1MjE2fQ.dzfQcmw7qfHLQen5IF-JhazKybRVjMKa0rOvI1ODs28

### Crear Usuarios directamente
POST {{server}}/
Content-Type: application/json

{
    "name":"Santiago",
    "surname":"garrido",
    "phone":"978457898",
    "email":"santiago1234@gmail.com",
    "password":"mariel1988"
}

### Registrar Usuarios
POST {{server}}/register
Content-Type: application/json

{
    "name":"Alguien",
    "surname":"Garrido",
    "phone":"965897878",
    "email":"alguien.garrido@gmail.com",
    "password":"mariel1988",
    "role": "basic"
}

### Logearse con Usuario
POST {{server}}/login
Content-Type: application/json

{
    "email":"amanda.garrido@gmail.com",
    "password":"mariel1988"
}

### Obtener todos los usuarios
GET {{server}}/
Authorization: Bearer {{token}}

### Obtener un usuario especifico
GET {{server}}/659caa4b99a4de9130d53a3b
Authorization: Bearer {{token}}

### Actualizar Usuario por id
PUT {{server}}/6579126cf6d8d976d3366935
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "role": "basic"
}

### Borrar un usuaeio por id
DELETE {{server}}/65a45b600a974ded8d6a4352