@server= http://localhost:3000/users

### Crear Usuarios directamente
POST {{server}}/
Content-Type: application/json

{
    "name":"Santiago",
    "surname":"garrido",
    "phone":"978457898",
    "email":"santiago1234@gmail.com",
    "password":"mariel1988"
}

### Registrar Usuarios
POST {{server}}/register
Content-Type: application/json

{
    "name":"Gustavo",
    "surname":"Tapia",
    "phone":"949606615",
    "email":"gustavogddddarrido.programador@gmail.com",
    "password":"mariel1988",
    "isAdmin": true
}

### Logearse con Usuario
POST {{server}}/login
Content-Type: application/json

{
    "email":"gustavogarrido5@gmail.com",
    "password":"mariel1988"
}

### Obtener todos los usuarios
GET {{server}}/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1N2EyNGIwZjUwMTBkMWU5YmJjODkzMSIsImlhdCI6MTcwMjgyMjEwOSwiZXhwIjoxNzAyODQzNzA5fQ.kRaQp8pR2UgC2tOmu6-nQTZhOETlwsVsm92HgcTe-48

### Obtener un usuario especifico
GET {{server}}/6579260521cba9dec12f45e4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NzkxMjZjZjZkOGQ5NzZkMzM2NjkzNSIsImlhdCI6MTcwMjgzMDg0OCwiZXhwIjoxNzAyODUyNDQ4fQ.RfD97W7sQL94cjK1BFNINQl2G7WoE0qIdfZj0AZs5L4

### Actualizar Usuario por id
PUT {{server}}/6579126cf6d8d976d3366935
Content-Type: application/json

{
    "isAdmin": false
}

### Borrar un usuaeio por id
DELETE {{server}}/657a82b843de89b34e76f07b