@server= http://localhost:3000/users

### Crear Usuarios directamente
POST {{server}}/
Content-Type: application/json

{
    "name":"Santiago",
    "surname":"garrido",
    "phone":"978457898",
    "email":"santiago1234@gmail.com",
    "password":"mariel1988"
}

### Registrar Usuarios
POST {{server}}/register
Content-Type: application/json

{
    "name":"Roberto",
    "surname":"Tapia",
    "phone":"949606615",
    "email":"gustavogddddarrido.programador2@gmail.com",
    "password":"mariel1988",
    "role": "administrator"
}

### Logearse con Usuario
POST {{server}}/login
Content-Type: application/json

{
    "email":"gustavogddddarrido.programador2@gmail.com",
    "password":"mariel1988"
}

### Obtener todos los usuarios
GET {{server}}/

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ODA2NDhlZDA3MjcyNmZkYTc3ZWYwYSIsImlhdCI6MTcwMjkxMzIwNiwiZXhwIjoxNzAyOTM0ODA2fQ.LJf0zJDpAkEaDq1k16L4X5rnrNjXq9Y7CKcwITvAJws

### Obtener un usuario especifico
GET {{server}}/6579260521cba9dec12f45e4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NzkxMjZjZjZkOGQ5NzZkMzM2NjkzNSIsImlhdCI6MTcwMjgzMDg0OCwiZXhwIjoxNzAyODUyNDQ4fQ.RfD97W7sQL94cjK1BFNINQl2G7WoE0qIdfZj0AZs5L4

### Actualizar Usuario por id
PUT {{server}}/6579126cf6d8d976d3366935
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ODA2NDhlZDA3MjcyNmZkYTc3ZWYwYSIsImlhdCI6MTcwMjkyMjIxMywiZXhwIjoxNzAyOTQzODEzfQ.q_NMUDcgGNdp6bHXkLWCSGKSQQwnNY7GR2zNDFSgKVM

{
    "role": "basic"
}

### Borrar un usuaeio por id
DELETE {{server}}/657a82b843de89b34e76f07b